리더보드 대규모 개선 및 메시지 매니저 개선
Sharlottes/thefinalsbot pull request #20
Opened 2024-08-06 12:14 UTC by Sharlottes

# 개요

리더보드를 개선하다가 이것저것 꼬리가 물려서 이참에 리더보드쪽 코드를 정리하고 전부터 점찍어둔 리팩토링들을 한번에 처리했습니다. pagination와 input를 모두 메시지 매니저화하고 keypad 입력을 새로 만들어두고 유기했습니다.

## 리더보드
* 기획 요청에 의해 임베드 색을 제외했습니다.
* 플렛폼과 버전을 매개변수로 받게끔 개선했습니다.
* 이에 따라 버전별로 다른 API 스키마 타입을 모두 명시했습니다. (api endpoint별 자동 추론은 낭비라고 보고 생략했습니다)
```ts
type LeaderBoardUserData =
  | LeaderBoardUserDataCB
  | LeaderBoardUserDataOB
  | LeaderBoardUserDataS1
  | LeaderBoardUserDataS2
  | LeaderBoardUserDataWT
  | LeaderBoardUserDataTA;
```
* 결과적으로 발생한 타입의 파편화 때문에 임베드 생성 로직도 수정을 거쳤습니다.
https://github.com/Sharlottes/thefinalsbot/blob/fix/update-to-s3/src/discord/commands/LeaderboardService.tsx#L373

* 리더보드에 있던 페이지네이션을 분리했습니다. 
```ts
const manager = await new PaginationMessageManager.Builder().send(
      "interaction",
      interaction,
      { size: result.data.count },
    );
manager.events.on("change", handleChange);
```
개발자는 이제 위와 같이 간편하게 메시지를 보내어 페이지네이션 제어를 매니저에게 일임시킬 수 있습니다.
> [!NOTE]
부가적인 기능의 성격을 띄는 페이지네이션과 달리, 원래 메시지 매니저는 해당 메시지의 모든 것을 통제하고 관리하는 것을 목적으로 뒀었습니다. 기존의 완전한 관리를 지향하는걸 유지할지, 아니면 부가기능의 성격을 주어 컴포지션이 가능케 할지는 나중에 생각해 볼 주제입니다.

* 페이지네이션을 분리하면서, 페이지네이션 자체도 개선했습니다.
1. 페이지 버튼을 눌러서 페이지 바로가기를 할 수 있습니다. 
2. 입력 형식은 서버 설정에서 사용한 `TextInput`를 메시지 매니저화한 `PrimitiveInputMessageManager`를 사용했습니다.
3. [1, size] 범위 내의 자연수만 받을 수 있도록 유효성 검사를 만들었습니다.
![Discord_PkS8F7xvw9](https://github.com/user-attachments/assets/53b20091-da26-48b7-919a-ae66875e1192)

* 위 움짤에서 보다시피 여러 유저들을 한눈에 볼 수 없던 기존 전적검색의 문제를 보완할 `/랭킹목록` 명령어를 만들었습니다.
1. 사실 이거 만들려고 페이지네이션 만든거나 다름없습니다.
2. 페이지를 바꿀 때마다 이미지를 새로 생성하여 재포스팅합니다. 이미지 생성을 위해 satori와 resvg로 html/css를 svg로 변환하여 png로 렌더링시켜서 Buffer를 얻고, 이걸 djs AttachmentBuilder에 담아 보냅니다.
3. 한 페이지마다 10명씩 랭크를 조회할 수 있습니다. 사진이 어디까지 길어도 될지 몰라서 10으로 고정했는데 이것도 인자를 받아볼까 생각중입니다

## 메시지 매니저
원래 메시지 매니저는 **메시지** 또는 인터렉션을 인자로 받아서 메시지를 보내고(send or reply), 응답받은 메시지를 캐싱하여 업데이트를 할 때마다 메시지를 edit하는 식으로 유지되어 왔습니다.
인터렉션이 없다면 메시지를 보내서 메시지를 얻고 넘겨야 하는 불편한 주고받음이 있었습니다. (waiting... 메시지)
이 문제를 해결하기 위해 Message 대신 TextBasedChannel (사실 좀 더 추상화된 PartialTextBasedChannelFields)를 받게 했습니다.
다만 `Discord.PartialTextBasedChannelFields | Discord.RepliableInteraction` 타입을 구성하는 타입들은 모두 클래스가 아니므로 분기 처리를 할 때 자동으로 추론할 수 없습니다. **즉, 무엇이 channel이고 무엇이 interaction인지 명시적으로 인자를 넘겨줘야 한단 불편함**이 이어지긴 했습니다. (그러나 UX적 불편을 DX적 불편으로 넘겼단 점에서 리팩토링 의의가 있다고 봅니다)
```ts
new ErrorMessageManager.Builder()
          .send("interaction", interaction, {
            description: `잘못된 버전입니다.
가능한 버전 값: ${validVersions.join(", ")}`,
          })
```
위 코드를 보면 특이하게도 Manager로부터 Builder를 참조하여 인스턴스를 만드는데, 이에 대해 이야기해봅시다.

디자인 패턴 관점에서: MessageManager의 빌더 패턴은 MessageManager 자체와 분리되어야 한다고 생각했습니다.
따라서 MessageManager를 build할 MessageBuilder를 만들었지만, MessageManager는 이름과 달리 싱글톤이 아니라 사용할 때마다 만들어지는 클래스고 ㅡ 설계 자체가 수많은 파생 클래스를 염두해두고 있으므로 MessageBuilder도 MessageManager의 파생 클래스마다 빌더를 만들어야 한단 결론에 도달합니다. 만약 그렇지 않는다면 빌더가 build한 객체는 항상 MessageManager이기 때문입니다.

이건 딱히 치명적인 문제는 아니지만, 빌더에서 build할 때 
```
class Builder extends MessageManager.Builder { 
  constructor(수많은인자들과타입들) { 
    super(Builder, ...params ) 
  } 
}
```
와 같은 코드를 매번 쓰는게 조금 불편했습니다. 그래서 아래와 같이 **클래스를 만드는 함수**를 만들었습니다. 
```ts
export default <T extends MessageManager, OT = any>(
  Manager: (new (
    message: Discord.Message,
    messageData: MessageData,
    options: OT,
  ) => T) &
    Pick<typeof MessageManager, "presetMessageData">,
) =>
  class MessageBuilder {}
```
위와 같이 정의된 함수는 `public static override Builder = MessageBuilder(PaginationMessageManager);` 와 같이 생성하여 static한 nested class를 쉽게 정의하는 데 도움을 줍니다.
모든 파생 클래스는 이 정적 필드를 필수적으로 가져야 하는데, **컴파일러 단에서 이걸 강제할 방법을 아직 발견하지 못해**서 아쉽습니다.

기존에 개발하고자 한 메시지 매니저는 한 메시지에 대해 편리하고 통일된 유지보수와 업데이트를 위한 클래스입니다.
그렇기에 단순히 알람만 보내는 메시지(AlertMessageManager)일수도, 에러를 보낼 수도, 입력을 요청할수도(InputMessageManager), 페이지네이션 기능을 제공할 수도(PaginationMessageManager) 있습니다.
그러나 바라고자 하는게 너무 커서 그런지 아쉬운 점도 있습니다. Message 자체가 djs로부터 비롯된지라 어쩔 수 없이 Message에 대한 쓰기 접근이 외부에 노출된단 점입니다. 이로 인한 문제로는 대표적으로 현재 모든 매니저와 매니저를 사용한 메시지는 매니저의 update 함수로 업데이트되어야 하지만, `interaction.replyUpdate`나 `message.edit`를 직접 사용한다면 **`MessageManager#messageData`의 값이 동기화되지 않는 문제**가 있습니다.

## 기타
* 메시지 매니저의 경로를 `embeds/` 에서 `messageManagers`로 보기 쉽게 바꿨습니다.
* Input에 약간의 리팩토링과 예외처리가 추가됐습니다.
* ButtonComponent를 만들었습니다. 이 ButtonBuilder 래퍼 클래스는 생성 인자로 클릭 콜백함수를 받게 설계됐습니다.
* 위의 내용 모두 읽으신거 맞죠?

2024-08-13 06:03 UTC, Cupelt requested changes
나머지는 제가 건들만한게 없어 보이네요

2024-08-13 06:30 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
거기까지 생각은 했지만 validation이 거슬려서 중복으로 미뤄둔 상태에요

2024-08-13 16:12 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
@Cupelt 오늘 슬커 유효성 검사를 확장한 SlashOption 래퍼 데코레이터를 만들려볼려고 했는데
https://github.com/discordx-ts/discordx/blob/main/packages/discordx/src/decorators/decorators/SlashOption.ts
구현보고 그만 정신이 나가버렸읍니다
그냥 중복해도 될 것 같아유...

2024-08-13 16:42 UTC, Cupelt commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
각각의 클래스로 분리 시키는것도 방법이에요.
`LeaderBoardProvider`
`LeaderBoardListCommand`
`LeaderBoardCommand`

로 분리해서,  `LeaderBoardListCommand`와 `LeaderBoardCommand`가 `LeaderBoardProvider`를 의존하게끔 하는것도 좋구요. 관련 작업을 Provider 클래스에 넣어줄 수 있으니, 조금더 깔끔하고, 개방폐쇄의 원칙을 더 잘 수행 할 수 있게 만들 수 있을 것 같아요.

2024-08-13 16:55 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
흠 아뇨 제말은 로직 추출 자체는 어렵지 않은데 리더보드 자체의 명령어 종류가 확장성이 낮은걸 생각해보면 삽질일테니 걍 중복으로 냅두잔거죠
굳이 추상화를 하자면 슬커와 슬커 유효성을 중심으로 추상화를 하는게 맞는데....
듣고보니 괜찮네요

```ts
class SlashOptionBuilder {
  constructor(
    public options: ApplicationCommandOptions,
    public validator : (value: unknown) => ({ isValid: true } | { isValid: false, reason: string })
  ){}
}
```
같은 형식으로 빼다가 쓰면 될 것 같네요. 내일하죠

2024-08-13 20:30 UTC, Cupelt commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
제 리뷰의 요지는 가독성이에요. 전체 코드 길이 404줄 중 현재 약 120줄 가량이 중복으로 사용중이라는 거에요. 이는 추후 확장이나, 수정에 장애물이 될 수도 있고, 버그를 야기할 수 있어요.

https://blog.naver.com/finway/221163007357

2024-08-14 06:13 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
이게 겨우 2개면서 깔끔한 조치가 없어 애매했는데 방법을 찾은 것 같네요

2024-08-15 16:59 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  ) {
@Cupelt 확인해주세용

2024-08-17 07:08 UTC, Cupelt requested changes
전 보단 나은데 보다보니까 더 보이네요 ㅋㅋㅋ

2024-08-17 07:16 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +    );
아 저거 prettier가 트롤하는거라 이 케이스를 만족하는 rule를 찾아야 합니다

2024-08-17 07:19 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +                : data.change}
https://the-finals-leaderboard.com/ 처럼 ^ v - 기호로 표현하고 싶었는데, svg 로드하는 부분이 시간을 잡아먹을 것 같아 로직을 미리 짜뒀읍니다.

2024-08-17 07:21 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +          <></>
그으으게... 사토리가 css 모듈을 지원하질 않아요..

>  Satori can't handle CSS files (or <style> tags) as that adds a lot of complexity. 
> https://github.com/vercel/satori/issues/541#issuecomment-1722357130

2024-08-17 07:21 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +    );
똑같이 prettier 트롤

2024-08-17 07:21 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +  }
👍

2024-08-17 07:22 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +      `https://api.the-finals-leaderboard.com/v1/leaderboard/${version}/${platform}?name=${target === "*" ? "" : target}`,
👍

2024-08-17 07:24 UTC, Cupelt commented on src/discord/messageManagers/MessageBuilder.ts
> +    ) {
`instanceof` 로 sender가 `PartialTextBasedChannelFields` 또는 `RepliableInteraction` 판별하는건 안되나요?

2024-08-17 07:28 UTC, Sharlottes commented on src/discord/messageManagers/MessageBuilder.ts
> +    ) {
네 진짜 환장하게도 그게 안됩니다. 
```ts
interface PartialTextBasedChannelFields<InGuild extends boolean = boolean> {
  send(options: string | MessagePayload | MessageCreateOptions): Promise<Message<InGuild>>;
}
type RepliableInteraction<Cached extends CacheType = CacheType> = Exclude<
  Interaction<Cached>,
  AutocompleteInteraction<Cached>
>;
```
둘 다 type라서 instanceof가 안돼요... 그래서 `send`나 `reply`같이 특정 속성의 존재 여부로 추론하는걸 생각하고 있긴 한데...깔끔하진 않죠

2024-08-17 07:29 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.tsx
> +                : data.change}
근데 두고보니 걍 svg보다 텍스트가 더 좋겠네요

2024-08-17 07:54 UTC, Cupelt requested changes

2024-08-17 07:54 UTC, Cupelt commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
이부분은, 변수로 빼도 될 것 같습니다

2024-08-17 07:54 UTC, Cupelt commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
이것도

2024-08-17 07:59 UTC, Sharlottes commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
👀 이걸 어디로 추출해놓나요?
구현도 간단하고, 사용처도 하나뿐인지라 저 검사 자체를 추상화하는건 아직 이르다고 봄니다

2024-08-17 07:59 UTC, Sharlottes commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
이하동문

2024-08-17 09:20 UTC, Cupelt commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
추상화라기 보다 구분화인데, 지금 보면 `ButtonComponent.create()` 부분에 뭔가 많이 구현되어 있어서, 조금 구분했으면 하는게 요지입니다

2024-08-17 09:20 UTC, Cupelt commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
코드는 가능하면 flat한게 가장 좋습니다

2024-08-17 10:02 UTC, Sharlottes commented on src/discord/messageManagers/PaginationMessageManager.ts
> +                    },
👍

2024-08-17 21:09 UTC, Cupelt approved these changes

2024-08-18 06:31 UTC, merged