Fix/deploy fail
Sharlottes/thefinalsbot pull request #30
Opened 2024-09-03 08:56 UTC by Sharlottes

배포단에서 초기화 과정 중 발생한 에러 해결

2024-09-05 00:23 UTC, Cupelt requested changes

2024-09-05 00:23 UTC, Cupelt commented on src/Vars.ts
> +            ),
언제봐도 nesting은 읽기 힘드네요

`./images/ranks` 는 따로 빼는게 좋아보여요
`path.resolve(publicDir, rankDir, file)`

2024-09-05 00:33 UTC, Sharlottes commented on src/Vars.ts
> +            ),
워우 이것만 보니 선 좀 씨게 넘었네요 확인

2024-09-08 04:14 UTC, Sharlottes commented on src/Vars.ts
> +            ),
@Cupelt https://github.com/Sharlottes/thefinalsbot/pull/30/commits/75d032dc64bab30a964feccad016de7d484c6d8b

2024-09-09 02:11 UTC, Cupelt commented on src/Vars.ts
> +            ),
이대로도 괜찮지만, 
https://stackoverflow.com/questions/67828499/second-layer-nested-promise 
요기 내용이 약간 도움이 될거 같기도 하고?? 아닌거 같기도 하고???

2024-09-09 02:11 UTC, Cupelt commented on src/Vars.ts
> +            ),
@Sharlottes

2024-09-09 02:44 UTC, Sharlottes commented on src/Vars.ts
> +            ),
> 이대로도 괜찮지만, https://stackoverflow.com/questions/67828499/second-layer-nested-promise 요기 내용이 약간 도움이 될거 같기도 하고?? 아닌거 같기도 하고???

IIFE보다 Promise가 더 명확한 전달이 될 것 같아서 일부러 명시한거에요(IIFE로 하면 바로 호출된다는 오해 소지)

2024-09-09 02:51 UTC, Cupelt commented on src/Vars.ts
> +            ),
~~제가 프로미스에 대해 잘 몰라요~~

2024-09-09 02:51 UTC, Cupelt approved these changes

2024-09-09 02:52 UTC, merged