Prov/roommaking
Sharlottes/thefinalsbot pull request #32
Opened 2024-09-09 05:50 UTC by Sharlottes

## Fixed Message 개선
* 이제 fixed message가 등록된 체널에는 fixed message 외의 메시지가 모두 삭제됩니다
* 같은 채널에 여러 fixed message가 있을 때 서로 엎치락뒤치락 하는 문제를 해결했습니다
* fixed message의 mongodb 컬렉션이 변경될 경우 자동으로 반영되도록 개선했습니다 (봇 재부팅 불필요)

## 방생성 개선
* 이제 방생성을 관리자가 명령어로 관리할 수 있습니다. (추가, 변경, 삭제, 조회)
* 일반 사용자는 지정된 채널에서 방생성 대시보드를 통해 방을 생성하고 링크를 공유할 수 있습니다.

![Discord_q6t5b0CwbZ](https://github.com/user-attachments/assets/18533254-3e0c-4bc1-bdd5-2fdeedd55738)

## Message Manager 개선
* Message Manager가 가진 몇가지 문제를 해결했습니다.
* builder를 삭제하고 팩토리 메서드를 manager가 정적으로 가지게 바꿨습니다.
* 매니저를 상속할 때 알아야 할 것이 몇가지 있습니다.
  * 생성자 옵션 타입이 정적 제너릭으로 믹스인 함수에 들어갔습니다. 개발자는 매니저를 상속할 때 이 생성자 옵션용 정적 제너릭을 무조건 넘겨줘야 합니다.
  * 만약 매니저가 임의의 고유 public 맴버를 정의했다면, 팩토리 메서드를 무조건 상속해야 합니다. 그렇지 않으면 팩토리 메서드는 항상 최상위 클래스인 `MessageManager`의 인스턴스를 반환할 것입니다. `OverWriteReturn` 커스텀 유틸 타입을 활용하세요.
  
```ts
  public declare static createOnChannel: OverwriteReturn<
    ReturnType<typeof MessageManager>["createOnChannel"],
    Promise<PaginationMessageManager>
  >;

  public declare static createOnInteraction: OverwriteReturn<
    ReturnType<typeof MessageManager>["createOnInteraction"],
    Promise<PaginationMessageManager>
  >;
```
    
  * 사전에 messageData를 바꿔야 한다면 `createMessageData`를, 사후에 manager를 사용해야 한다면 `createManager`를 override하세요.
  ```ts
  protected static override async createMessageData({
    description,
    footer,
  }: ErrorMessageOptions) {
    const messageData = await super.createMessageData({});
    messageData.embeds = [
      new Discord.EmbedBuilder()
        .setColor(PColors.error)
        .setTitle("이런!")
        .setDescription(description || null)
        .setFooter(
          footer
            ? {
                text: footer[0],
                iconURL: footer[1],
              }
            : null,
        ),
    ];
    return messageData;
  }
  ```
  
  * api 변경으로 인해 유즈케이스 코드가 변경되었습니다. e.g ErrorMessageManager를 보자면
```ts
new ErrorMessageManager.Builder()
  .send("interaction", interaction, {
    description: errorMsg,
  });
```
가 아래와 같이 바뀜으로써 DX가 크게 개선되었습니다.
```ts
ErrorMessageManager.createOnInteraction(interaction, {
  description: errorMsg,
}, {
  ephemeral: true
});
```
또한 ephemeral와 같이 MessageCreateOptions의 일부를 3번째 파라미터로 받게 하여 기존에 불가능했던 ephemeral 메시지 수신이 가능해졌습니다.

* InputMessageManager에 취소 버튼이 추가되었습니다. 이로 인해 value 필드가 항상 nullable하므로 입력을 끝마치고 널 체크를 통해 사용자가 취소를 했는지 무조건 확인해야 합니다.

## 기타
* server-init가 이미 있는 상태에서 해당 채널이 새로 생성될 경우, 이전 채널을 삭제합니다

2024-09-10 13:57 UTC, Cupelt requested changes
실제로 바꿀만한건 하나!

2024-09-10 13:57 UTC, Cupelt commented on src/core/FixedMessageRegister.ts
> +    );
약간 이런거 정리 할 때, 의도적으로 공백 칸을 넣거나, `Promise.all(map(e => {`를 한줄에 넣어서 정돈되게 할 수도 있어요.

```ts
await Promise.all(allData.map(async (data) => {
  const guild = await Vars.client.guilds.fetch(data.guildId);

  await Promise.all(data.channels.map(async (channelId) => {
    const channel = await guild.channels.fetch(channelId);
    if (!channel || !channel.isTextBased()) 
      return;

    const messages = await channel.messages.fetch();

    await Promise.all(messages.map(async (m) => {
      if (m.author == Vars.client.user) await m.delete();
    }));
  }));
}));
```

2024-09-10 13:57 UTC, Cupelt commented on src/core/FixedMessageRegister.ts
> +    );
이렇게 하면 코드의 깊이를 가늠하기 쉽고, 분리되어 있는 느낌을 줄 수 있을 거 같아요
### 리뷰 아님! 참고용

2024-09-11 03:55 UTC, Sharlottes commented on src/core/FixedMessageRegister.ts
>      console.time("initalizing FixedMessageRegister...");
https://github.com/Sharlottes/thefinalsbot/commit/acce64e79dae58c5f48af73bd013255cb058de63 👍

2024-09-11 03:58 UTC, Sharlottes commented on src/core/FixedMessageRegister.ts
> +    );
intent의 대부분은 사악한 prettier의 만행입니다
그런데 간격 띄우기는 까먹었네유 바로 반영
https://github.com/Sharlottes/thefinalsbot/commit/1a688d1b28ac02d20a53c2388dfad1f818c05113 👍

2024-09-11 05:41 UTC, Cupelt commented on src/core/FixedMessageRegister.ts
> +    );
> intend의 대부분은 사악한 prettier의 만행입니다 그런데 간격 띄우기는 까먹었네유 바로 반영 [1a688d1](https://github.com/Sharlottes/thefinalsbot/commit/1a688d1b28ac02d20a53c2388dfad1f818c05113) 👍

그런의미로 printWidth 의 확장을....

2024-09-11 05:53 UTC, Sharlottes commented on src/Vars.ts
> +      ) {
https://github.com/Sharlottes/thefinalsbot/commit/8cb074a37f2608a5364e86a862ab661fc760317f +40 늘렸읍니다

2024-09-11 06:16 UTC, Cupelt approved these changes

2024-09-11 06:17 UTC, merged