Hotfix/node mem sizeup
Sharlottes/thefinalsbot pull request #37
Opened 2024-09-23 10:30 UTC by Sharlottes

* 힙메모리 오버플로 문제점 해결
  * 확인된 이벤트 리스너들은 수명이 다하면 off하도록 수명주기 설정
  * 수명이 없지만 끝없이 생성할 수 있는 리스너들은 임의의 시한부 수명 부여(ex: 15분)
* #36 망할 button component 삭제
* 리더보드 전반적인 개선
  * 레이아웃 개선: 제목을 이미지에서 content로 이동. hash id는 작게, name는 크게. rank/score/cash 숫자는 모두 서식화. 10개 표시에서 10 / 10개 이중 표시로 개선
  * 리더보드 렌더링 최적화 (otf -> woff 폰트파일 전환)
  * UX 개선
    * 페이지 바로가기, 닉네임 찾기(이후 페이지 바로가기), 처음/끝으로 가기 버튼 추가
    * 옵션 한글화 및 힌트 제공
![image](https://github.com/user-attachments/assets/6e6f6744-3d92-44ef-8ecf-4fc7ea79f841)
    * 클베1에서 랭크 이미지를 찾을 수 없는 해결
    * 일부 경우에서 이름 텍스트가 overflow하는 문제 표면적으로 해결(?)
      - 실제 textwrap나 flexwrap가 구현되지 않은지 wrap를 직접할 수 밖에 없어짐
    * 
* 맨날 뜨던 "--experience-loader" flag 경고 해결

2024-09-25 04:17 UTC, Cupelt requested changes

2024-09-25 04:17 UTC, Cupelt commented on src/discord/commands/LeaderboardService.ts
> +          }
이거 함수로 따로 빼서 한번에 묶은 이유가 있나요?

2024-09-25 04:17 UTC, Cupelt commented on src/discord/commands/LeaderboardService.ts
> +          }
가장 크게 눈에 띄는건 이거밖에 없는거 같은데

2024-09-25 06:52 UTC, Sharlottes commented on src/discord/commands/LeaderboardService.ts
> +          }
저거 Vars.client에 리스너로 등록된걸텐데 저 메시지가 사라지면 컴포넌트에 접근할 방법이 없으니 리스너를 회수해야 해서요

2024-09-29 09:03 UTC, Cupelt approved these changes

2024-09-29 09:09 UTC, merged